---
- name: Verificar actualizaciones de Windows
  hosts: all
  gather_facts: false
  become: yes                  # Indica que se usará elevación
  become_method: runas         # Método de elevación para Windows
  become_user: awxupdate       # Usuario administrador local
  tasks:
    - name: Obtener actualizaciones pendientes
      win_shell: |
        Import-Module PSWindowsUpdate
        Get-WindowsUpdate -MicrosoftUpdate -IgnoreReboot |
          Select-Object KBArticleID,Title,Size,Classification |
          ConvertTo-Json
      register: updates

    - name: Mostrar actualizaciones
      debug:
        var: updates.stdout
